/**:
  ros__parameters:
    # 基础参数配置
    save_directory: "out/camera_output"
    upload_url: "http://192.168.58.161:8090/device_file/upload"

    # 优化参数，用于滤波与性能优化
    marker_length: 0.05
    smoothing_alpha: 0.6
    stability_window_size: 3
    stability_position_threshold: 0.05
    detect_interval: 0.1

    # ArUco 碰撞检测相关参数
    target_frame: "base_link"