/**:
  ros__parameters:
    # 原点
    item_above_car_point: [-350.0, 234.0, 117.0]

    # 机械臂放置物品到车上的点位
    item_in_car_point: [-350.0, 400.0, -212.0]

    # 机械臂到达柜子前面点位【顺序是从上往下增大】
    cabinet_front_points: |
      - [-77, 400, -13]
      - [0, 0, 0]
      - [0, 0, 0]
      - [0, 0, 0]
      - [-77, 400, 715

    # 进入柜子放置物品点位
    cabinet_inside_points: |
      - [-77, 620, -13]
      - [0, 0, 0]
      - [0, 0, 0]
      - [0, 0, 0]
      - [-77, 620, 715]

    # 在柜子前识别物品点位
    cabinet_recognize_points: |
      - [-77, 400, -113]
      - [0, 0, 0]
      - [0, 0, 0]
      - [0, 0, 0]
      - [-77, 400, 607]

    # 点在车上的夹爪角度
    # 左A：180,0,-90
    # 右B：-180,0,-90
    car_point_posture: [180,0,-90]

    # 点在柜子的夹爪角度
    # 左A：90,0,180
    # 右B：-90,0,0
    cabinet_point_posture: [90,0,180]

    # 夹爪抓取物品时x轴的旋转期望（相对于世界坐标系）
    desired_gripper_rotation_x: [0,-1,0]
