/**:
  ros__parameters:
    # 原点
    item_above_car_point: [-512.0, 0.0, 176.0]

    # 机械臂放置物品到车上的点位
    item_in_car_point: [-512.0, 0.0, 10.0]

    # 机械臂到达柜子前面点位【顺序是从上往下增大】
    cabinet_front_points:
      - "[-77, -400, 500]"
      - "[0, 0, 0]"
      - "[0, 0, 0]"
      - "[0, 0, 0]"
      - "[-100, -500, 600]"

    # 进入柜子放置物品点位
    cabinet_inside_points:
      - "[-77, -400, 600]"
      - "[0, 0, 0]"
      - "[0, 0, 0]"
      - "[0, 0, 0]"
      - "[-100, -720, 700]"

    # 在柜子前识别物品点位
    cabinet_recognize_points:
      - "[0, 0, 0]"
      - "[0, 0, 0]"
      - "[0, 0, 0]"
      - "[0, 0, 0]"
      - "[-100, -500, 600]"

    # 点在车上的夹爪角度
    # 左A：180,0,-90
    # 右B：-180,0,-90
    car_point_posture: [180.0,0.0,90.0]

    # 点在柜子的夹爪角度
    # 左A：90,0,180
    # 右B：-90,0,0
    cabinet_point_posture: [-90.0,0.0,180.0]

    # 夹爪抓取物品时x轴的旋转期望（相对于世界坐标系）
    desired_gripper_rotation_x: [0.0,-1.0,0.0]
